////
    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
////

:log4j-url: {logging-services-url}/log4j/2.x
:log4j-api-url: {log4j-url}/manual/api-separation.html

= Log4j Scala API

{project-name} provides a Scala-friendly interface to log against {log4j-api-url}[the Log4j API].
It supports Scala `2.10`, `2.11`, `2.12`, `2.13`, and `3`.

[IMPORTANT]
====
This is just a logging API.
Your application still needs to have a logging backend (e.g., {log4j-url}[Log4j]) configured.
====

[#dependencies]
== Dependencies

You need to have the `org.apache.logging.log4j:log4j-api-scala` dependency in your classpath:

[source,sbt,subs="+attributes"]
----
libraryDependencies ++= Seq(
  "org.apache.logging.log4j" %% "log4j-api-scala" % "{project-version}"
)
----

Java module name is set to `org.apache.logging.log4j.api.scala`.
OSGi ``Bundle-SymbolicName``s are set to `org.apache.logging.log4j.api.scala.2.10`, `org.apache.logging.log4j.api.scala.2.11`, and so on.

[#usage]
== Usage

Using the Scala API is as simple as mixing in the `Logging` trait to your class:

[source,scala]
----
import org.apache.logging.log4j.scala.Logging
import org.apache.logging.log4j.Level

class MyClass extends BaseClass with Logging {

  def doStuff(): Unit = {
    logger.info("Doing stuff")
  }

  def doStuffWithLevel(level: Level): Unit = {
    logger(level, "Doing stuff with arbitrary level")
  }

  def doStuffWithUser(user: User): Unit = {
    logger.info(s"Doing stuff with ${user.getName}.")
  }

}
----

[#params]
== Parameter substitution

Unlike in Java, Scala provides native functionality for string interpolation https://docs.scala-lang.org/overviews/core/string-interpolation.html[beginning in Scala 2.10].
As all logger calls are implemented as macros, using string interpolation directly does not require additional if checks:

[source,scala]
----
logger.debug(s"Logging in user ${user.getName} with birthday ${user.calcBirthday}")
----

[#flow-logging]
== Flow logging

The Scala API supports flow logging (tracing method entry and exit) via `traceEntry` and `traceExit` methods.
Starting from version `13.2.0`, `traceEntry` is safe to use with `null` parameters and evaluates arguments lazily, ensuring no overhead or crashes when trace logging is disabled.

[source,scala]
----
def doSomething(foo: String, bar: Int): Unit = {
  logger.traceEntry(foo, bar)
  // do something
}
----

[#logger-names]
== Logger names

Most logging implementations use a hierarchical scheme for matching logger names with logging configuration.
In this scheme the logger name hierarchy is represented by `.` characters in the logger name, in a fashion very similar to the hierarchy used for Java/Scala package names.
The `Logger` property added by the `Logging` trait follows this convention: the trait ensures the `Logger` is automatically named according to the class it is being used in.
