staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/scala


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 26106
# - Commit ID: 8a1646c6b58a2533598c628d1cfa38af0e35279e
# - Timestamp: 2024-09-09T11:01:18Z
