staging:
  profile: ~
  whoami: main-site-stg-out
  subdir: content/log4j/scala


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 16296
# - Commit ID: d18a332d7e8108aeed61293006e37db2dbe54a25
# - Timestamp: 2024-04-22T19:52:04Z
